spring.application.name=testmanagement
server.address=0.0.0.0
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3307/testmanagement?useSSL=false&&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

token.signing.key=Zm9vYmFyYmF6cXV4c3l6d2VydHkxMjM0NTY3ODkwMTIzNA==

# Jenkins Configuration
jenkins.job-url=http://10.0.0.15:8080/job/JmeterTest/buildWithParameters
jenkins.user=admin
jenkins.token=11d1741c72084f7b0ebd2144638320e8d2
jenkins.callback-token=5c7af1e8-ba95-442f-a5e2-d0f18c7051e6
